const CONNECTION = 'CONNECTION';
const SETTINGS = 'SETTINGS';
const CALIBRATION = 'CALIBRATION';
const MEASUREMENT = 'MEASUREMENT';
const DISCONNECTION = 'DISCONNECTION';
const CONNECTION_STATUS = 'CONNECTION_STATUS';
const CURRENT_ACTION = 'CURRENT_ACTION';
const CONNECT_SOCKET = 'CONNECT_SOCKET';
const DISCONNECT_SOCKET = 'DISCONNECT_SOCKET';
const DEVICE_CONNECTION = 'DEVICE_CONNECTION';
const DEVICE_DISCONNECTION = 'DEVICE_DISCONNECTION';
const DISCONNECT_DEVICE = 'DISCONNECT_DEVICE';
const VERIFY_DEVICE_CONNECTION = 'VERIFY_DEVICE_CONNECTION';
const SHOW_DIALOG = 'SHOW_DIALOG';
const SOCKET_CONNECTION = 'SOCKET_CONNECTION';
const SOCKET_DISCONNECT_CLEANLY = 'SOCKET_DISCONNECT_CLEANLY';
const UPDATE_DEVICE_RECONNECTION = 'UPDATE_DEVICE_RECONNECTION';
const CLIENT_SOCKET_ALREADY_EXIST = 'CLIENT_SOCKET_ALREADY_EXIST';
const DISCONNECT_DEVICE_FROM_SERVER = 'DISCONNECT_DEVICE_FROM_SERVER';

// colorgate
const COLOR_GATE_API_REQ = 'COLOR_GATE_API_REQ';
const COLOR_GATE_API_RES = 'COLOR_GATE_API_RES';
const COLOR_GATE_SERVER_CONNECTION_REQ = 'COLOR_GATE_SERVER_CONNECTION_REQ';
const COLOR_GATE_SERVER_CONNECTION_RES = 'COLOR_GATE_SERVER_CONNECTION_RES';
const COLOR_GATE_CONNECTION_CHECK = 'COLOR_GATE_CONNECTION_CHECK';
const COLOR_GATE_UPDATE_LICENSE = 'COLOR_GATE_UPDATE_LICENSE';

// alwan
const ALWAN_API_REQ = 'ALWAN_API_REQ';
const ALWAN_API_RES = 'ALWAN_API_RES';
const ALWAN_SERVER_CONNECTION_REQ = 'ALWAN_SERVER_CONNECTION_REQ';
const ALWAN_SERVER_CONNECTION_RES = 'ALWAN_SERVER_CONNECTION_RES';
const ALWAN_CONNECTION_CHECK = 'ALWAN_CONNECTION_CHECK';
const ALWAN_UPDATE_LICENSE = 'ALWAN_UPDATE_LICENSE';

// chartScanning
const CHART_POSITION = 'CHART_POSITION';
const GRAB_INITIAL_POSITION = 'GRAB_INITIAL_POSITION';

// precision balance
const WEIGHT_MEASUREMENT = 'WEIGHT_MEASUREMENT';
const MAKE_RESET_DEVICE = 'MAKE_RESET_DEVICE';
const GET_TARE_VALUE = 'GET_TARE_VALUE';
const SET_TARE_VALUE = 'SET_TARE_VALUE';

// zebra printer
const ZEBRA_PRINTER_HANDLER = 'ZEBRA_PRINTER_HANDLER';
const BAR_CODE_READER_HANDLER = 'BAR_CODE_READER_HANDLER';
const SWITCH_TO_YS3060_CONNECTION_MODE = 'SWITCH_TO_YS3060_CONNECTION_MODE';

module.exports = {
  CONNECTION,
  SETTINGS,
  CALIBRATION,
  MEASUREMENT,
  DISCONNECTION,
  CONNECTION_STATUS,
  CURRENT_ACTION,
  CONNECT_SOCKET,
  DISCONNECT_SOCKET,
  DEVICE_CONNECTION,
  VERIFY_DEVICE_CONNECTION,
  SHOW_DIALOG,
  DISCONNECT_DEVICE,
  SOCKET_CONNECTION,
  SOCKET_DISCONNECT_CLEANLY,
  UPDATE_DEVICE_RECONNECTION,
  CLIENT_SOCKET_ALREADY_EXIST,
  DEVICE_DISCONNECTION,
  DISCONNECT_DEVICE_FROM_SERVER,
  COLOR_GATE_API_REQ,
  COLOR_GATE_API_RES,
  COLOR_GATE_SERVER_CONNECTION_REQ,
  COLOR_GATE_SERVER_CONNECTION_RES,
  COLOR_GATE_CONNECTION_CHECK,
  COLOR_GATE_UPDATE_LICENSE,
  ALWAN_API_REQ,
  ALWAN_API_RES,
  ALWAN_SERVER_CONNECTION_REQ,
  ALWAN_SERVER_CONNECTION_RES,
  ALWAN_CONNECTION_CHECK,
  ALWAN_UPDATE_LICENSE,
  CHART_POSITION,
  GRAB_INITIAL_POSITION,
  WEIGHT_MEASUREMENT,
  MAKE_RESET_DEVICE,
  GET_TARE_VALUE,
  SET_TARE_VALUE,
  ZEBRA_PRINTER_HANDLER,
  BAR_CODE_READER_HANDLER,
  SWITCH_TO_YS3060_CONNECTION_MODE,
};
